_wandb:
    value:
        cli_version: 0.25.0
        e:
            8d6imk289bo1vdwgkucve64556z0gjik:
                codePath: run_logging.py
                codePathLocal: run_logging.py
                cpu_count: 56
                cpu_count_logical: 112
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "2005769203712"
                        used: "1675264094208"
                email: wguo6358@gmail.com
                executable: /home/wg25r/miniconda/envs/neg/bin/python3
                git:
                    commit: 7fa3062878f8aca41a34eb61474a8ba3a213a092
                    remote: https://github.com/weathon/review_agent.git
                gpu: NVIDIA RTX A6000
                gpu_count: 3
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-058c2ff8-0e0d-ba79-96b8-99c5bdc85e8e
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-190dcde2-2149-850b-6892-63dd9bfac5a2
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-223f1d69-b595-dd22-d112-fae575ae6ef4
                host: shandu.ws.ok.ubc.ca
                memory:
                    total: "810125402112"
                os: Linux-6.8.0-94-generic-x86_64-with-glibc2.35
                program: /home/wg25r/review_agent/run_logging.py
                python: CPython 3.11.14
                root: /home/wg25r/review_agent
                startedAt: "2026-04-01T23:29:31.887515Z"
                writerId: 8d6imk289bo1vdwgkucve64556z0gjik
        m: []
        python_version: 3.11.14
        t:
            "4": 3.11.14
            "5": 0.25.0
            "12": 0.25.0
            "13": linux-x86_64
